version: "3.9"
services:
  sandbox-app:
    image: sandbox-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: sandbox
      POSTGRES_PASSWORD: sandbox
