on:
  push:
    branches:
      - main

name: Deploy to AWS

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    environment: production

    steps:
      - name: Update Docker Compose CLI
        run: |
          curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials from Sandbox account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.SANDBOX_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SANDBOX_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create Docker ECS context
        run: |
          docker context create ecs sandboxapp --from-env

      - name: Use Docker ECS context
        run: |
          docker context use sandboxapp

      - name: Deploy using Docker Compose
        run: |
          docker compose up
